# Generated by Django 5.0.3 on 2024-04-30 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('configuracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('uuid_carrito', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('fechaDeCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente', verbose_name='Cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario sistema')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
            },
        ),
        migrations.CreateModel(
            name='PartidasCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(verbose_name='Cantidad')),
                ('sku', models.CharField(max_length=150, verbose_name='SKU')),
                ('departamento', models.CharField(max_length=45, null=True, verbose_name='Departamento')),
                ('familia', models.CharField(max_length=100, null=True, verbose_name='Familia')),
                ('marca', models.CharField(max_length=45, null=True, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=1000, verbose_name='Nombre del producto')),
                ('claveSAT', models.CharField(max_length=45, null=True, verbose_name='Clave SAT')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Descuento')),
                ('precioUnitario', models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Precio unitario')),
                ('total', models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Total')),
                ('tasaIVA', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='Tasa de IVA')),
                ('tasaIEPS', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='Tasa de IEPS')),
                ('IVA', models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='IVA')),
                ('IEPS', models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='IEPS')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='ventas.carrito', verbose_name='Carrito')),
            ],
            options={
                'verbose_name': 'Partida carrito',
                'verbose_name_plural': 'Partidas carrito',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('documentType', models.CharField(choices=[('TK', 'Ticket'), ('NV', 'Nota de Venta'), ('FA', 'Factura'), ('OT', 'Orden de Trabajo')], max_length=3)),
                ('folio', models.PositiveIntegerField()),
                ('carrito', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='info_venta', serialize=False, to='ventas.carrito', verbose_name='Carrito')),
                ('fechaDeVenta', models.DateTimeField(verbose_name='Fecha de venta')),
                ('observaciones', models.CharField(blank=True, max_length=150, verbose_name='Observaciones')),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Subtotal')),
                ('IVA', models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='IVA')),
                ('IEPS', models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='IEPS')),
                ('Total', models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Total')),
                ('devolucion', models.BooleanField(default=False, verbose_name='Devuelto?')),
                ('garantia', models.BooleanField(default=False, verbose_name='Solicitud de garantia?')),
                ('cancelado', models.BooleanField(default=False, verbose_name='Cancelado?')),
                ('ticketFile', models.FileField(blank=True, null=True, upload_to='tickets/%Y/%m/%d/', verbose_name='Ticket de pago en PDF')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.caja', verbose_name='Caja')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.empleados', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
    ]
