# Generated by Django 5.0.3 on 2024-04-30 14:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDeTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentType', models.CharField(choices=[('TK', 'Ticket'), ('NV', 'Nota de Venta'), ('FA', 'Factura'), ('OT', 'Orden de Trabajo')], max_length=3)),
                ('folio', models.PositiveIntegerField()),
                ('last_status', models.CharField(choices=[('1', 'En espera'), ('2', 'En proceso'), ('3', 'Excepción'), ('4', 'Listo para entrega'), ('5', 'Orden Cerrada'), ('6', 'Orden Cerrada y cobrada')], max_length=1, verbose_name='Estado de la OT')),
                ('fecha_ultimo_evento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ultima actualización')),
                ('observaciones', models.TextField(blank=True, default='', max_length=1000, verbose_name='Observaciones')),
                ('nombre_cliente', models.TextField(max_length=200, verbose_name='Nombre del cliente')),
                ('telefono', models.TextField(blank=True, max_length=15, null=True, verbose_name='Telefono de contacto')),
                ('anticipo', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Anticipo')),
                ('total', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Total')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orden_trabajo', to='configuracion.caja', verbose_name='Caja')),
                ('carrito', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orden_trabajo', to='ventas.carrito', verbose_name='Carrito asociado a OT')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orden_trabajo', to='configuracion.empleados', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Orden de trabajo',
                'verbose_name_plural': 'Ordenes de trabajo',
            },
        ),
        migrations.CreateModel(
            name='eventosOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('tipo_de_evento', models.CharField(choices=[('1', 'En espera'), ('2', 'En proceso'), ('3', 'Excepción'), ('4', 'Listo para entrega'), ('5', 'Orden Cerrada'), ('6', 'Orden Cerrada y cobrada')], max_length=1, verbose_name='Estado de la OT')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('id_OT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='taller.ordendetrabajo', verbose_name='Eventos del OT')),
            ],
            options={
                'verbose_name': 'Evento de OT',
                'verbose_name_plural': 'Eventos de OT',
            },
        ),
    ]
