services:
  db:
    container_name: mysql-${SERVER_NAME}
    image: mysql:8.0.35
    volumes:
      - mysql-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} 
      - MYSQL_DATABASE=${MYSQL_DATABASE} 
      - MYSQL_USER=${MYSQL_USER} 
      - MYSQL_PASSWORD=${MYSQL_PASSWORD} 
    healthcheck:
      test: ["CMD-SHELL", 'mysql --database=$$MYSQL_DATABASE --password=$$MYSQL_ROOT_PASSWORD --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
      interval: 30s
      timeout: 10s
      retries: 4
    ports:
      - "3306:3306"

  web:
    build: 
      context: ./
      dockerfile: ./backend/Dockerfile-dev
    container_name: backend-${SERVER_NAME}
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./backend/.env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE} 
      - MYSQL_USER=${MYSQL_USER} 
      - MYSQL_PASSWORD=${MYSQL_PASSWORD} 
      - MYSQL_HOST=mysql-${SERVER_NAME}
    volumes:
      - ./backend:/backend
      - static_files:/backend/static
      - media_files:/backend/media
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  mysql-db:
  static_files:
  media_files:
