#Dev Image
FROM python:3.12.0-slim

ENV PYTHONUNBUFFERED 1
RUN mkdir /backend
RUN mkdir /backend/static
RUN mkdir /backend/media

RUN mkdir /react

COPY ./backend/requirements.txt /backend
RUN apt-get update && apt-get install -y pkg-config gcc default-libmysqlclient-dev pkg-config
RUN pip install --no-cache-dir -r /backend/requirements.txt
WORKDIR /backend

