# Generated by Django 5.0.3 on 2024-04-30 14:35

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, max_length=250, null=True, verbose_name='Nombre de caja')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Clave de empleado')),
                ('first_name', models.TextField(max_length=256, verbose_name='Nombre')),
                ('last_name', models.TextField(blank=True, max_length=256, verbose_name='Apellidos')),
                ('observaciones', models.TextField(blank=True, max_length=250, null=True, verbose_name='observaciones')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.TextField(blank=True, null=True, verbose_name='Calle')),
                ('no_ext', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número exterior:')),
                ('no_int', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número interior')),
                ('colonia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Colonia')),
                ('localidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidad')),
                ('municipio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio')),
                ('estado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
                ('pais', models.CharField(blank=True, max_length=50, null=True, verbose_name='País')),
                ('cp', models.CharField(max_length=12, verbose_name='CP')),
                ('nombre', models.TextField(max_length=256)),
                ('razonSocial', models.CharField(max_length=250, null=True)),
                ('RFC', models.CharField(max_length=250, null=True)),
                ('regimenFiscal', models.CharField(max_length=250, null=True)),
                ('telefono', models.TextField(null=True)),
                ('email', models.EmailField(max_length=256, null=True)),
                ('logo', models.ImageField(null=True, upload_to='logos/')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activar_integracion_MP', models.BooleanField(verbose_name='Activar integracion mercado pago')),
                ('open_print_ticket', models.BooleanField(verbose_name='Abrir ventana para impresion de ticket siempre')),
                ('caja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='configuracion.caja')),
            ],
            options={
                'verbose_name': 'Configuracion Caja',
                'verbose_name_plural': 'Configuracion Cajas',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.TextField(blank=True, max_length=256, null=True, verbose_name='Nombre')),
                ('last_name', models.TextField(blank=True, max_length=256, null=True, verbose_name='Apellidos')),
                ('descripcion', models.TextField(blank=True, max_length=250, null=True, verbose_name='Descripción')),
                ('cliente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configuracion.caja')),
                ('empleado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configuracion.empleados')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='empleados',
            name='sucursal',
            field=models.ManyToManyField(to='configuracion.sucursal'),
        ),
        migrations.CreateModel(
            name='ConsecutivosSucursales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentType', models.CharField(choices=[('TK', 'Ticket'), ('NV', 'Nota de Venta'), ('FA', 'Factura'), ('OT', 'Orden de Trabajo')], max_length=3, verbose_name='Tipo de Doc.')),
                ('consecutivo', models.PositiveBigIntegerField(verbose_name='Consecutivo')),
                ('id_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Consecutivo de sucursal',
                'verbose_name_plural': 'Consecutivos de sucursales',
            },
        ),
        migrations.AddField(
            model_name='caja',
            name='sucursal',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='configuracion.sucursal'),
        ),
    ]
