# Generated by Django 5.0.3 on 2024-04-30 14:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detalleMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=256, verbose_name='Descripción')),
                ('fechaDeMovimiento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del movimiento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Monto del movimiento')),
                ('formaDePago', models.CharField(choices=[('EF', 'Efectivo'), ('TB', 'Transferencia bancaria'), ('TD', 'Tarjeta de Debito'), ('TC', 'Tarjeta de Credito'), ('CH', 'Cheque'), ('UN', 'Otros')], max_length=2, verbose_name='Forma de pago')),
                ('modalidadDePago', models.CharField(choices=[('PAR', 'Parcialidades'), ('UNA', 'Una sola exhibición')], max_length=3, verbose_name='Modalidad de pago')),
                ('banco', models.TextField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('referencia', models.TextField(blank=True, max_length=100, null=True, verbose_name='Referencia bancaria')),
                ('montoEfectivo', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Monto pagado en Efectivo')),
                ('montoCambioEfectivo', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Monto devuelto en efectivo')),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='configuracion.caja', verbose_name='ID Caja')),
                ('venta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalle_pago', to='ventas.venta', verbose_name='ID Venta')),
            ],
            options={
                'verbose_name': 'Detalle de movimiento',
                'verbose_name_plural': 'Detalle de movimientos',
            },
        ),
    ]
